apiVersion: v1 
kind: ServiceAccount 
metadata:
  name: kafka-scripts-pod-service-account
  namespace: scripting-services
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.ROLE_ARN }}
    eks.amazonaws.com/audience: "sts.amazonaws.com"